Импорт библиотеки numpy

Создание единичной матрицы 4 на 4 с элементами типа int64, которые умножилимь на 6

In [122]:
import numpy as np
a=np.eye(4, dtype='int64')*6
print(a)

[[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 6]]


Размерность матрицы

In [123]:
a.shape

(4, 4)

Создание нулевой матрицы размером 4 на 4 с элементами типа int64

In [124]:
b=np.zeros((4, 4), dtype='int64')
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Создание матрицы с элементами от 0 до 10000 с шагом 1000

In [125]:
c=np.arange(0, 10000+1, 1000)
c

array([    0,  1000,  2000,  3000,  4000,  5000,  6000,  7000,  8000,
        9000, 10000])

Элементы матрицы от 2 до 12 с шагом 3 равны 6

In [126]:
c[1:12:3]=6
c

array([   0,    6, 2000, 3000,    6, 5000, 6000,    6, 8000, 9000,    6])

Умножение матриц

Операция выполнилась успешно, так как размеры матриц позволяют их умножить

In [127]:
a*b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Создание единичной матрицы 4 на 4 типа float64

Все элементы матрицы стали равны косинусу своего значения

In [128]:
d=np.eye(4, dtype="float64")
d[::]=np.cos(a)
d

array([[0.96017029, 1.        , 1.        , 1.        ],
       [1.        , 0.96017029, 1.        , 1.        ],
       [1.        , 1.        , 0.96017029, 1.        ],
       [1.        , 1.        , 1.        , 0.96017029]])

Округлить значения матрицы до 2 знаков после запятой

In [129]:
np.round(d, 2)

array([[0.96, 1.  , 1.  , 1.  ],
       [1.  , 0.96, 1.  , 1.  ],
       [1.  , 1.  , 0.96, 1.  ],
       [1.  , 1.  , 1.  , 0.96]])

Округлить элементы матрицы в большую сторону

In [130]:
np.ceil(d)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Округлить элементы матрицы в меньшую сторону

In [131]:
np.fix(d)

array([[0., 1., 1., 1.],
       [1., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 1., 1., 0.]])

Элементы каждой из 4 матриц были просуммированы между собой, а затем суммы элементов этих матриц были сложены между собой

In [132]:
k=np.sum(a)+np.sum(b)+np.sum(c)+np.sum(d)
k

np.float64(33063.840681146605)

Умножение и сложение матриц

In [133]:
a*d+d

array([[6.72119201, 1.        , 1.        , 1.        ],
       [1.        , 6.72119201, 1.        , 1.        ],
       [1.        , 1.        , 6.72119201, 1.        ],
       [1.        , 1.        , 1.        , 6.72119201]])

Матрица преобразована в вектор-столбец

In [134]:
a.reshape((16, 1))

array([[6],
       [0],
       [0],
       [0],
       [0],
       [6],
       [0],
       [0],
       [0],
       [0],
       [6],
       [0],
       [0],
       [0],
       [0],
       [6]])

Вектор-столбец стал вектор-строкой через операцию транспонирования

In [135]:
np.transpose(a.reshape((16, 1)))

array([[6, 0, 0, 0, 0, 6, 0, 0, 0, 0, 6, 0, 0, 0, 0, 6]])

К элементам матрицы прибавилось рандомное число от 0 до 1

In [136]:
a+np.random.random()

array([[6.55361167, 0.55361167, 0.55361167, 0.55361167],
       [0.55361167, 6.55361167, 0.55361167, 0.55361167],
       [0.55361167, 0.55361167, 6.55361167, 0.55361167],
       [0.55361167, 0.55361167, 0.55361167, 6.55361167]])

Перемножение матриц со случайными числами от -3 до 3

In [155]:
np.random.randn(2, 2)*np.random.randn(2, 2)

array([[-0.34321397,  0.16812535],
       [ 2.46723565, -0.40938641]])